### ISSUE TITLE
Cant write file in sub directory

### ISSUE THREAD

**Issue by rafilkmp3** [timheuer/base64-to-file#14]
```
      - name: Write json in sub dir
        id: write_google_services_json
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: "./native/App_Resources/Android/google-services.json"
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}
```

When I try do this I get this error

```
/home/runner/work/_actions/timheuer/base64-to-file/v1.0.3/dist/index.js:75
      if (err) throw err;
               ^

[Error: ENOENT: no such file or directory, open '/home/runner/work/_te***/home/runner/work/front/front/native/App_Resources/Android/google-services.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/_te***/home/runner/work/front/front/native/App_Resources/Android/google-services.json'
}
```

I need a intermediary step to move the file to right path now as my workaround, but would be nice to write a file to destination
