### ISSUE TITLE
 Temporary file value is not set

### ISSUE THREAD

**Issue by CodemenschenAndroid** [timheuer/base64-to-file#48]
- name: Fetch credential file from secrets
        id: fetch_credential_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'credential_file.json'
          encodedString: ${{ secrets.CREDENTIAL_FILE_CONTENT }}

![image](https://user-images.githubusercontent.com/60087122/207839803-06b81915-12f9-44a0-8e1e-a71ee0855cc9.png)

**Comment by timheuer** [comment]
Oh no! @CodemenschenAndroid is there any chance you can provide more detail on the run? OS runner details and such?

I'm assuming this is hosted agents and that there is indeed a value in the secrets in the repository that this run has access to?

**Comment by awesomund** [comment]
I experienced this error today while using this action in a reusable workflow. When using it directly in a workflow, however, it works as intended.

**Comment by timheuer** [comment]
Interesting, @awesomund can you explain a bit more (or share a workflow file)? I am assuming you mean a composite action? I'd love to see the config to replicate and see if that's the issue...

**Comment by CodemenschenAndroid** [comment]
@timheuer yes

**Comment by CodemenschenAndroid** [comment]
Image: ubuntu-22.04
  Version: 20221212.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20221212.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221212.1

**Comment by CodemenschenAndroid** [comment]
Run on : ubuntu-latest

**Comment by awesomund** [comment]
@timheuer Below is a slightly simplified version of my use case - build and upload an android app, split up into two actions.

```
name: Build Android App Bundle
on: [workflow_call, workflow_dispatch]

jobs:
  build_android_app_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Decode and save keystore to file
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: stuff/upload-key.jks
          encodedString: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./android/gradlew
      - name: Run Android build script
        run: sh android-prod-build.sh
        env:
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          UPLOAD_KEY_ALIAS: ${{ secrets.UPLOAD_KEY_ALIAS }}

```

```
name: Upload Android App Bundle

on: workflow_dispatch

jobs:
  build-android-app-bundle:
    name: Build app bundle
    uses: my-org/my-repo/.github/workflows/build_android_app.yml@main
  upload-android-app-bundle:
    needs: build-android-app-bundle
    runs-on: ubuntu-latest
    steps:
      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./android/app/build/outputs/bundle/release/app-release.aab
```

The first workflow ("Build Android App Bundle") works as intended when it runs separately.

The second workflow ("Upload Android App Bundle") calls the first workflow, but the step using the `base64-to-file@v1`-action fails with the message `Error: Temporary file value is not set`

**Comment by timheuer** [comment]
What a tricky one @CodemenschenAndroid and @awesomund thanks for logging it.  Apparently with reusable workflows the secrets are NOT naturally passed through.  So your "Upload" one is failing because the secret input is 0 bytes and fails writing anything.  In your upload add `secrets: inherit` to the build job like this:

```
jobs:
  build-android-app-bundle:
    name: Build app bundle
    uses: my-org/my-repo/.github/workflows/build_android_app.yml@main
    secrets: inherit
```
And I believe that will fix it.  Please let me know.  This is what fixed it for me.

**Comment by awesomund** [comment]
@timheuer `secrets: inherit` did the trick for me. Thank you!

**Comment by timheuer** [comment]
Great! I’ll close this issue.

@all-contributors please add @awesomund and @CodemenschenAndroid for bug

**Comment by timheuer** [comment]
@all-contributors please add @CodemenschenAndroid for bug

**Comment by nblfikr** [comment]
hi, @timheuer . I using it directly in a workflow, but not working properly

![image](https://user-images.githubusercontent.com/56732307/215087331-b618be39-6438-4889-8f7e-6c3a542148f9.png)

my workflow like this

```
name: Build App

on:
  push:
    branches:
      - master

jobs:
  build_android_app_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Decode upload-keystore.jks
        id: decode_upload_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: upload-keystore.jks
          encodeString: ${{ secrets.UPLOAD_KEYSTORE }}
```

I was try adding `secrets: inherit` too, but same error occurred
